# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
install:
- R -e 'install.packages("devtools")'
- R -e 'devtools::install_deps(dep = T)'
script:
- R CMD build .
- R CMD check
- Rscript -e 'devtools::test()'
after_success:
  - Rscript -e 'covr::codecov()'
